package domain;
// Generated Jul 10, 2013 10:55:17 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Auditory generated by hbm2java
 */
public class Auditory  implements java.io.Serializable, eltc.web.DictionaryInterface {


     private Integer id;
     private String name;
     private String user;
     private Date insertDatetime;
     private Set timetables = new HashSet(0);

    public Auditory() {
    }

	
    public Auditory(String name, Date insertDatetime) {
        this.name = name;
        this.insertDatetime = insertDatetime;
    }
    public Auditory(String name, String user, Date insertDatetime, Set timetables) {
       this.name = name;
       this.user = user;
       this.insertDatetime = insertDatetime;
       this.timetables = timetables;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }
    public Set getTimetables() {
        return this.timetables;
    }
    
    public void setTimetables(Set timetables) {
        this.timetables = timetables;
    }




}


