package domain;
// Generated Jul 10, 2013 10:55:17 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Certificate generated by hbm2java
 */
public class Certificate  implements java.io.Serializable {


     private Integer id;
     private Vendor vendor;
     private String code;
     private String name;
     private String user;
     private Date insertDatetime;
     private Set trainerCertificates = new HashSet(0);

    public Certificate() {
    }

	
    public Certificate(Vendor vendor, String code, String name, Date insertDatetime) {
        this.vendor = vendor;
        this.code = code;
        this.name = name;
        this.insertDatetime = insertDatetime;
    }
    public Certificate(Vendor vendor, String code, String name, String user, Date insertDatetime, Set trainerCertificates) {
       this.vendor = vendor;
       this.code = code;
       this.name = name;
       this.user = user;
       this.insertDatetime = insertDatetime;
       this.trainerCertificates = trainerCertificates;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Vendor getVendor() {
        return this.vendor;
    }
    
    public void setVendor(Vendor vendor) {
        this.vendor = vendor;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }
    public Set getTrainerCertificates() {
        return this.trainerCertificates;
    }
    
    public void setTrainerCertificates(Set trainerCertificates) {
        this.trainerCertificates = trainerCertificates;
    }




}


