package domain;
// Generated Jul 10, 2013 10:55:17 AM by Hibernate Tools 3.2.1.GA



/**
 * City1 generated by hbm2java
 */
public class City1  implements java.io.Serializable {


     private Integer id;
     private Country1 country1;
     private String name;
     private String addInfo;

    public City1() {
    }

	
    public City1(Country1 country1, String name) {
        this.country1 = country1;
        this.name = name;
    }
    public City1(Country1 country1, String name, String addInfo) {
       this.country1 = country1;
       this.name = name;
       this.addInfo = addInfo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Country1 getCountry1() {
        return this.country1;
    }
    
    public void setCountry1(Country1 country1) {
        this.country1 = country1;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddInfo() {
        return this.addInfo;
    }
    
    public void setAddInfo(String addInfo) {
        this.addInfo = addInfo;
    }




}


