package domain;
// Generated Jul 10, 2013 10:55:17 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City  implements java.io.Serializable {


     private Integer id;
     private Country country;
     private String name;
     private String user;
     private Date insertDatetime;
     private Set organizationsForCityFactId = new HashSet(0);
     private Set organizationsForCityOfficialId = new HashSet(0);

    public City() {
    }

	
    public City(Country country, String name, Date insertDatetime) {
        this.country = country;
        this.name = name;
        this.insertDatetime = insertDatetime;
    }
    public City(Country country, String name, String user, Date insertDatetime, Set organizationsForCityFactId, Set organizationsForCityOfficialId) {
       this.country = country;
       this.name = name;
       this.user = user;
       this.insertDatetime = insertDatetime;
       this.organizationsForCityFactId = organizationsForCityFactId;
       this.organizationsForCityOfficialId = organizationsForCityOfficialId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }
    public Set getOrganizationsForCityFactId() {
        return this.organizationsForCityFactId;
    }
    
    public void setOrganizationsForCityFactId(Set organizationsForCityFactId) {
        this.organizationsForCityFactId = organizationsForCityFactId;
    }
    public Set getOrganizationsForCityOfficialId() {
        return this.organizationsForCityOfficialId;
    }
    
    public void setOrganizationsForCityOfficialId(Set organizationsForCityOfficialId) {
        this.organizationsForCityOfficialId = organizationsForCityOfficialId;
    }




}


