package domain;
// Generated Jul 10, 2013 10:55:17 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Contract generated by hbm2java
 */
public class Contract implements java.io.Serializable, eltc.web.DeletableInterface {

    private Integer id;
    private Organization organization;
    private String number;
    private String numberInternal;
    private Date date;
    private String description;
    private String pdfFile;
    private String wordFile;
    private boolean deleted;
    private String user;
    private Date insertDatetime;
    private Set timetableStudents = new HashSet(0);

    public Contract() {
    }

    public Contract(Organization organization, String number, Date date, Date insertDatetime) {
        this.organization = organization;
        this.number = number;
        this.date = date;
        this.insertDatetime = insertDatetime;
    }

    public Contract(Organization organization, String number, Date date, String description, String pdfFile, String wordFile,String user, Date insertDatetime, Set timetableStudents) {
        this.organization = organization;
        this.number = number;
        this.date = date;
        this.description = description;
        this.pdfFile = pdfFile;
        this.wordFile = wordFile;
        this.user = user;
        this.insertDatetime = insertDatetime;
        this.timetableStudents = timetableStudents;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Organization getOrganization() {
        return this.organization;
    }

    public void setOrganization(Organization organization) {
        this.organization = organization;
    }

    public String getNumber() {
        return this.number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getPdfFile() {
        return this.pdfFile;
    }

    public void setPdfFile(String pdfFile) {
        this.pdfFile = pdfFile;
    }

    public String getWordFile() {
        return wordFile;
    }

    public void setWordFile(String wordFile) {
        this.wordFile = wordFile;
    }
    

    public String getUser() {
        return this.user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public Date getInsertDatetime() {
        return this.insertDatetime;
    }

    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }

    public Set getTimetableStudents() {
        return this.timetableStudents;
    }

    public void setTimetableStudents(Set timetableStudents) {
        this.timetableStudents = timetableStudents;
    }

    public boolean isDeleted() {
        return deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    public String getNumberInternal() {
        return numberInternal;
    }

    public void setNumberInternal(String numberInternal) {
        this.numberInternal = numberInternal;
    }
}
