package domain;
// Generated Jul 10, 2013 10:55:17 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Country1 generated by hbm2java
 */
public class Country1  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set city1s = new HashSet(0);

    public Country1() {
    }

	
    public Country1(String name) {
        this.name = name;
    }
    public Country1(String name, Set city1s) {
       this.name = name;
       this.city1s = city1s;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getCity1s() {
        return this.city1s;
    }
    
    public void setCity1s(Set city1s) {
        this.city1s = city1s;
    }




}


