package domain;
// Generated Jul 10, 2013 10:55:17 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * CourseSpecialization generated by hbm2java
 */
public class CourseSpecialization  implements java.io.Serializable {


     private Integer id;
     private Course course;
     private Specialization specialization;
     private String user;
     private Date insertDatetime;

    public CourseSpecialization() {
    }

	
    public CourseSpecialization(Course course, Specialization specialization, Date insertDatetime) {
        this.course = course;
        this.specialization = specialization;
        this.insertDatetime = insertDatetime;
    }
    public CourseSpecialization(Course course, Specialization specialization, String user, Date insertDatetime) {
       this.course = course;
       this.specialization = specialization;
       this.user = user;
       this.insertDatetime = insertDatetime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public Specialization getSpecialization() {
        return this.specialization;
    }
    
    public void setSpecialization(Specialization specialization) {
        this.specialization = specialization;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }




}


