package domain;
// Generated Jul 10, 2013 10:55:17 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CourseOfficial generated by hbm2java
 */
public class CourseOfficial  implements java.io.Serializable, eltc.web.DeletableInterface {


     private Integer id;
     private Course course;
     private CourseType courseType;
     private String code;
     private String additionalInfo;
     private String user;
     private boolean deleted;
     private Date insertDatetime;
     private Set courseOfficialPrices = new HashSet(0);
     private Set timetableStudents = new HashSet(0);

    public CourseOfficial() {
    }

	
    public CourseOfficial(Course course, CourseType courseType, String code, Date insertDatetime) {
        this.course = course;
        this.courseType = courseType;
        this.code = code;
        this.insertDatetime = insertDatetime;
    }
    public CourseOfficial(Course course, CourseType courseType, String code, String additionalInfo, String user, Date insertDatetime, Set courseOfficialPrices, Set timetableStudents) {
       this.course = course;
       this.courseType = courseType;
       this.code = code;
       this.additionalInfo = additionalInfo;
       this.user = user;
       this.insertDatetime = insertDatetime;
       this.courseOfficialPrices = courseOfficialPrices;
       this.timetableStudents = timetableStudents;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public CourseType getCourseType() {
        return this.courseType;
    }
    
    public void setCourseType(CourseType courseType) {
        this.courseType = courseType;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getAdditionalInfo() {
        return this.additionalInfo;
    }
    
    public void setAdditionalInfo(String additionalInfo) {
        this.additionalInfo = additionalInfo;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }
    public Set getCourseOfficialPrices() {
        return this.courseOfficialPrices;
    }
    
    public void setCourseOfficialPrices(Set courseOfficialPrices) {
        this.courseOfficialPrices = courseOfficialPrices;
    }
    public Set getTimetableStudents() {
        return this.timetableStudents;
    }
    
    public void setTimetableStudents(Set timetableStudents) {
        this.timetableStudents = timetableStudents;
    }

    public boolean isDeleted() {
        return deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }




}


