package domain;
// Generated Jul 10, 2013 10:55:17 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course implements java.io.Serializable, eltc.web.DeletableInterface {

    private Integer id;
    private Vendor vendor;
    private Category category;
    private String codeOwn;
    private String nameOriginal;
    private String nameRu;
    private String discriptionEn;
    private String discriptionRu;
    private int durationDays;
    private int durationHours;
    private String additionalInfo;
    private boolean deleted;
    private String user;
    private Date insertDatetime;
    private Set courseOfficials = new HashSet(0);
    private Set trainerPassedCourses = new HashSet(0);
    private Set timetables = new HashSet(0);
    private Set courseSpecializations = new HashSet(0);

    public Course() {
    }

    public Course(Vendor vendor, Category category, String codeOwn, String nameOriginal, String nameRu, String discriptionEn, String discriptionRu, byte durationDays, byte durationHours, Date insertDatetime) {
        this.vendor = vendor;
        this.category = category;
        this.codeOwn = codeOwn;
        this.nameOriginal = nameOriginal;
        this.nameRu = nameRu;
        this.discriptionEn = discriptionEn;
        this.discriptionRu = discriptionRu;
        this.durationDays = durationDays;
        this.durationHours = durationHours;
        this.insertDatetime = insertDatetime;
    }

    public Course(Vendor vendor, Category category, String codeOwn, String nameOriginal, String nameRu, String discriptionEn, String discriptionRu, byte durationDays, byte durationHours, String additionalInfo, String user, Date insertDatetime, Set courseOfficials, Set trainerPassedCourses, Set timetables, Set courseSpecializations) {
        this.vendor = vendor;
        this.category = category;
        this.codeOwn = codeOwn;
        this.nameOriginal = nameOriginal;
        this.nameRu = nameRu;
        this.discriptionEn = discriptionEn;
        this.discriptionRu = discriptionRu;
        this.durationDays = durationDays;
        this.durationHours = durationHours;
        this.additionalInfo = additionalInfo;
        this.user = user;
        this.insertDatetime = insertDatetime;
        this.courseOfficials = courseOfficials;
        this.trainerPassedCourses = trainerPassedCourses;
        this.timetables = timetables;
        this.courseSpecializations = courseSpecializations;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Vendor getVendor() {
        return this.vendor;
    }

    public void setVendor(Vendor vendor) {
        this.vendor = vendor;
    }

    public Category getCategory() {
        return this.category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    public String getCodeOwn() {
        return this.codeOwn;
    }

    public void setCodeOwn(String codeOwn) {
        this.codeOwn = codeOwn;
    }

    public String getNameOriginal() {
        return this.nameOriginal;
    }

    public void setNameOriginal(String nameOriginal) {
        this.nameOriginal = nameOriginal;
    }

    public String getNameRu() {
        return this.nameRu;
    }

    public void setNameRu(String nameRu) {
        this.nameRu = nameRu;
    }

    public String getDiscriptionEn() {
        return this.discriptionEn;
    }

    public void setDiscriptionEn(String discriptionEn) {
        this.discriptionEn = discriptionEn;
    }

    public String getDiscriptionRu() {
        return this.discriptionRu;
    }

    public void setDiscriptionRu(String discriptionRu) {
        this.discriptionRu = discriptionRu;
    }

    public int getDurationDays() {
        return this.durationDays;
    }

    public void setDurationDays(int durationDays) {
        this.durationDays = durationDays;
    }

    public int getDurationHours() {
        return this.durationHours;
    }

    public void setDurationHours(int durationHours) {
        this.durationHours = durationHours;
    }

    public String getAdditionalInfo() {
        return this.additionalInfo;
    }

    public void setAdditionalInfo(String additionalInfo) {
        this.additionalInfo = additionalInfo;
    }

    public String getUser() {
        return this.user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public Date getInsertDatetime() {
        return this.insertDatetime;
    }

    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }

    public Set getCourseOfficials() {
        return this.courseOfficials;
    }

    public void setCourseOfficials(Set courseOfficials) {
        this.courseOfficials = courseOfficials;
    }

    public Set getTrainerPassedCourses() {
        return this.trainerPassedCourses;
    }

    public void setTrainerPassedCourses(Set trainerPassedCourses) {
        this.trainerPassedCourses = trainerPassedCourses;
    }

    public Set getTimetables() {
        return this.timetables;
    }

    public void setTimetables(Set timetables) {
        this.timetables = timetables;
    }

    public Set getCourseSpecializations() {
        return this.courseSpecializations;
    }

    public void setCourseSpecializations(Set courseSpecializations) {
        this.courseSpecializations = courseSpecializations;
    }

    public boolean isDeleted() {
        return deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }
        

}
