package domain;
// Generated Jul 10, 2013 10:55:17 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * CourseOfficialPrice generated by hbm2java
 */
public class CourseOfficialPrice  implements java.io.Serializable, eltc.web.DeletableInterface {


     private Integer id;
     private Currency currency;
     private CourseOfficial courseOfficial;
     private Date date;
     private Float price;
     private boolean deleted;
     private String user;
     private Date insertDatetime;

    public CourseOfficialPrice() {
    }

	
    public CourseOfficialPrice(Currency currency, CourseOfficial courseOfficial, Date date, Date insertDatetime) {
        this.currency = currency;
        this.courseOfficial = courseOfficial;
        this.date = date;
        this.insertDatetime = insertDatetime;
    }
    public CourseOfficialPrice(Currency currency, CourseOfficial courseOfficial, Date date, Float price, String user, Date insertDatetime) {
       this.currency = currency;
       this.courseOfficial = courseOfficial;
       this.date = date;
       this.price = price;
       this.user = user;
       this.insertDatetime = insertDatetime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Currency getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(Currency currency) {
        this.currency = currency;
    }
    public CourseOfficial getCourseOfficial() {
        return this.courseOfficial;
    }
    
    public void setCourseOfficial(CourseOfficial courseOfficial) {
        this.courseOfficial = courseOfficial;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Float getPrice() {
        return this.price;
    }
    
    public void setPrice(Float price) {
        this.price = price;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }

    public boolean isDeleted() {
        return deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }




}


