package domain;
// Generated Dec 25, 2013 9:36:04 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.Set;

/**
 * Email generated by hbm2java
 */
public class Email implements java.io.Serializable {

    private Integer id;
    private Student student;
    private EmailType emailType;
    private String email;
    private boolean isActual;
    private boolean subscribe;
    private String user;
    private Date insertDatetime;

    public Email() {
    }

    
    

    public Email(String email, boolean isActual, boolean subscribe, Date insertDatetime) {
        this.email = email;
        this.isActual = isActual;
        this.subscribe = subscribe;
        this.insertDatetime = insertDatetime;
    }

    public Email(Student student, EmailType emailtype, String email, boolean isActual, boolean subscribe, String user, Date insertDatetime) {
        this.student = student;
        this.emailType = emailtype;
        this.email = email;
        this.isActual = isActual;
        this.subscribe = subscribe;
        this.user = user;
        this.insertDatetime = insertDatetime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Student getStudent() {
        return this.student;
    }

    public void setStudent(Student student) {
        this.student = student;
    }

    public EmailType getEmailType() {
        return emailType;
    }

    public void setEmailType(EmailType emailType) {
        this.emailType = emailType;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public boolean isIsActual() {
        return isActual;
    }

    public void setIsActual(boolean isActual) {
        this.isActual = isActual;
    }

    public boolean isSubscribe() {
        return subscribe;
    }

    public void setSubscribe(boolean subscribe) {
        this.subscribe = subscribe;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public Date getInsertDatetime() {
        return insertDatetime;
    }

    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }
}
