package domain;
// Generated Jul 10, 2013 10:55:17 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * OrganizationHrManager generated by hbm2java
 */
public class OrganizationHrManager  implements java.io.Serializable {


     private Integer id;
     private Organization organization;
     private HrManager hrManager;
     private Boolean isActual;
     private String user;
     private Date insertDatetime;

    public OrganizationHrManager() {
    }

	
    public OrganizationHrManager(Organization organization, HrManager hrManager, Date insertDatetime) {
        this.organization = organization;
        this.hrManager = hrManager;
        this.insertDatetime = insertDatetime;
    }
    public OrganizationHrManager(Organization organization, HrManager hrManager, Boolean isActual, String user, Date insertDatetime) {
       this.organization = organization;
       this.hrManager = hrManager;
       this.isActual = isActual;
       this.user = user;
       this.insertDatetime = insertDatetime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Organization getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(Organization organization) {
        this.organization = organization;
    }
    public HrManager getHrManager() {
        return this.hrManager;
    }
    
    public void setHrManager(HrManager hrManager) {
        this.hrManager = hrManager;
    }
    public Boolean getIsActual() {
        return this.isActual;
    }
    
    public void setIsActual(Boolean isActual) {
        this.isActual = isActual;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }




}


