package domain;
// Generated Jul 10, 2013 10:55:17 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Sex generated by hbm2java
 */
public class Sex  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set hrManagers = new HashSet(0);
     private Set trainers = new HashSet(0);
     private Set students = new HashSet(0);

    public Sex() {
    }

	
    public Sex(String name) {
        this.name = name;
    }
    public Sex(String name, Set hrManagers, Set trainers, Set students) {
       this.name = name;
       this.hrManagers = hrManagers;
       this.trainers = trainers;
       this.students = students;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getHrManagers() {
        return this.hrManagers;
    }
    
    public void setHrManagers(Set hrManagers) {
        this.hrManagers = hrManagers;
    }
    public Set getTrainers() {
        return this.trainers;
    }
    
    public void setTrainers(Set trainers) {
        this.trainers = trainers;
    }
    public Set getStudents() {
        return this.students;
    }
    
    public void setStudents(Set students) {
        this.students = students;
    }




}


