package domain;
// Generated Jul 10, 2013 10:55:17 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Specialization generated by hbm2java
 */
public class Specialization  implements java.io.Serializable, eltc.web.DictionaryInterface {


     private Integer id;
     private String name;
     private String user;
     private Date insertDatetime;
     private Set courseSpecializations = new HashSet(0);
     private Set trainerSpecializations = new HashSet(0);

    public Specialization() {
    }

	
    public Specialization(String name, Date insertDatetime) {
        this.name = name;
        this.insertDatetime = insertDatetime;
    }
    public Specialization(String name, String user, Date insertDatetime, Set courseSpecializations, Set trainerSpecializations) {
       this.name = name;
       this.user = user;
       this.insertDatetime = insertDatetime;
       this.courseSpecializations = courseSpecializations;
       this.trainerSpecializations = trainerSpecializations;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }
    public Set getCourseSpecializations() {
        return this.courseSpecializations;
    }
    
    public void setCourseSpecializations(Set courseSpecializations) {
        this.courseSpecializations = courseSpecializations;
    }
    public Set getTrainerSpecializations() {
        return this.trainerSpecializations;
    }
    
    public void setTrainerSpecializations(Set trainerSpecializations) {
        this.trainerSpecializations = trainerSpecializations;
    }




}


