package domain;
// Generated Jul 10, 2013 10:55:17 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable, eltc.web.DeletableInterface, eltc.web.PersonInterface {

    private Integer id;
    private String lastNameRu;
    private String firstNameRu;
    private String patronicNameRu;
    private String lastNameEn;
    private String firstNameEn;
    private String patronicNameEn;
    private Date dateOfBirth;
    private Sex sex;
    private String phoneHome;
    private String phoneMobile1;
    private String phoneMobile2;
    private String phoneOffice;
    private String skype;
    private String icq;
    private String mailruAgent;
    private String comments;
    private String photo;
    private String personVueIdent;
    private String prometricIdent;
    private String oracleLogin;
    private String microsoftLogin;
    private boolean deleted;
    private String user;
    private Date insertDatetime;
    private Set timetableStudents = new HashSet(0);
    private Set emails = new HashSet(0);
    private Set studentOrganizations = new HashSet(0);


    public Student() {
    }
    public Student(Sex sex, String lastNameRu, String firstNameRu, String patronicNameRu, String lastNameEn, String firstNameEn, Date insertDatetime) {
        this.sex = sex;
        this.lastNameRu = lastNameRu;
        this.firstNameRu = firstNameRu;
        this.patronicNameRu = patronicNameRu;
        this.lastNameEn = lastNameEn;
        this.firstNameEn = firstNameEn;
        this.insertDatetime = insertDatetime;
    }

    public Student(Sex sex, String lastNameRu, String firstNameRu, String patronicNameRu, String lastNameEn, String firstNameEn, String patronicNameEn, Date dateOfBirth, String phoneHome, String phoneMobile1, String phoneMobile2, String phoneOffice, String skype, String icq, String mailruAgent, String comments, String photo, String personVueIdent, String prometricIdent, String oracleLogin, String microsoftLogin, String user, Date insertDatetime, Set timetableStudents, Set emails) {
        this.sex = sex;
        this.lastNameRu = lastNameRu;
        this.firstNameRu = firstNameRu;
        this.patronicNameRu = patronicNameRu;
        this.lastNameEn = lastNameEn;
        this.firstNameEn = firstNameEn;
        this.patronicNameEn = patronicNameEn;
        this.dateOfBirth = dateOfBirth;
        this.phoneHome = phoneHome;
        this.phoneMobile1 = phoneMobile1;
        this.phoneMobile2 = phoneMobile2;
        this.phoneOffice = phoneOffice;
        this.skype = skype;
        this.icq = icq;
        this.mailruAgent = mailruAgent;
        this.comments = comments;
        this.photo = photo;
        this.personVueIdent = personVueIdent;
        this.prometricIdent = prometricIdent;
        this.oracleLogin = oracleLogin;
        this.microsoftLogin = microsoftLogin;
        this.user = user;
        this.insertDatetime = insertDatetime;
        this.timetableStudents = timetableStudents;
        this.emails = emails;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Sex getSex() {
        return this.sex;
    }

    public void setSex(Sex sex) {
        this.sex = sex;
    }

    public String getLastNameRu() {
        return this.lastNameRu;
    }

    public void setLastNameRu(String lastNameRu) {
        this.lastNameRu = lastNameRu;
    }

    public String getFirstNameRu() {
        return this.firstNameRu;
    }

    public void setFirstNameRu(String firstNameRu) {
        this.firstNameRu = firstNameRu;
    }

    public String getPatronicNameRu() {
        return this.patronicNameRu;
    }

    public void setPatronicNameRu(String patronicNameRu) {
        this.patronicNameRu = patronicNameRu;
    }

    public String getLastNameEn() {
        return this.lastNameEn;
    }

    public void setLastNameEn(String lastNameEn) {
        this.lastNameEn = lastNameEn;
    }

    public String getFirstNameEn() {
        return this.firstNameEn;
    }

    public void setFirstNameEn(String firstNameEn) {
        this.firstNameEn = firstNameEn;
    }

    public String getPatronicNameEn() {
        return this.patronicNameEn;
    }

    public void setPatronicNameEn(String patronicNameEn) {
        this.patronicNameEn = patronicNameEn;
    }

    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }

    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public String getPhoneHome() {
        return this.phoneHome;
    }

    public void setPhoneHome(String phoneHome) {
        this.phoneHome = phoneHome;
    }

    public String getPhoneMobile1() {
        return this.phoneMobile1;
    }

    public void setPhoneMobile1(String phoneMobile1) {
        this.phoneMobile1 = phoneMobile1;
    }

    public String getPhoneMobile2() {
        return this.phoneMobile2;
    }

    public void setPhoneMobile2(String phoneMobile2) {
        this.phoneMobile2 = phoneMobile2;
    }

    public String getPhoneOffice() {
        return this.phoneOffice;
    }

    public void setPhoneOffice(String phoneOffice) {
        this.phoneOffice = phoneOffice;
    }

    public String getSkype() {
        return this.skype;
    }

    public void setSkype(String skype) {
        this.skype = skype;
    }

    public String getIcq() {
        return this.icq;
    }

    public void setIcq(String icq) {
        this.icq = icq;
    }

    public String getMailruAgent() {
        return this.mailruAgent;
    }

    public void setMailruAgent(String mailruAgent) {
        this.mailruAgent = mailruAgent;
    }

    public String getComments() {
        return this.comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public String getPhoto() {
        return this.photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getPersonVueIdent() {
        return this.personVueIdent;
    }

    public void setPersonVueIdent(String personVueIdent) {
        this.personVueIdent = personVueIdent;
    }

    public String getPrometricIdent() {
        return this.prometricIdent;
    }

    public void setPrometricIdent(String prometricIdent) {
        this.prometricIdent = prometricIdent;
    }

    public String getOracleLogin() {
        return this.oracleLogin;
    }

    public void setOracleLogin(String oracleLogin) {
        this.oracleLogin = oracleLogin;
    }

    public String getMicrosoftLogin() {
        return this.microsoftLogin;
    }

    public void setMicrosoftLogin(String microsoftLogin) {
        this.microsoftLogin = microsoftLogin;
    }

    public String getUser() {
        return this.user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public Date getInsertDatetime() {
        return this.insertDatetime;
    }

    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }

    public Set getTimetableStudents() {
        return this.timetableStudents;
    }

    public void setTimetableStudents(Set timetableStudents) {
        this.timetableStudents = timetableStudents;
    }

    public Set getEmails() {
        return emails;
    }

    public void setEmails(Set emails) {
        this.emails = emails;
    }

    public boolean isDeleted() {
        return deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }
    
    
//    @Override
//    public String toString() {
//        return "Student{" + "id=" + id + ", sex=" + sex + ", lastNameRu=" + lastNameRu + ", firstNameRu=" + firstNameRu + ", patronicNameRu=" + patronicNameRu + ", lastNameEn=" + lastNameEn + ", firstNameEn=" + firstNameEn + ", patronicNameEn=" + patronicNameEn + ", dateOfBirth=" + dateOfBirth + ", emailOffice=" + emailOffice + ", emailHome=" + emailHome + ", emailAdd=" + emailAdd + ", phoneHome=" + phoneHome + ", phoneMobile1=" + phoneMobile1 + ", phoneMobile2=" + phoneMobile2 + ", phoneOffice=" + phoneOffice + ", skype=" + skype + ", icq=" + icq + ", mailruAgent=" + mailruAgent + ", comments=" + comments + ", photo=" + photo + ", personVueIdent=" + personVueIdent + ", prometricIdent=" + prometricIdent + ", oracleLogin=" + oracleLogin + ", microsoftLogin=" + microsoftLogin + ", deleted=" + deleted + ", user=" + user + ", insertDatetime=" + insertDatetime + ", timetableStudents=" + timetableStudents + '}';
//    }

    public Set getStudentOrganizations() {
        return studentOrganizations;
    }

    public void setStudentOrganizations(Set studentOrganizations) {
        this.studentOrganizations = studentOrganizations;
    }
}
