package domain;
// Generated Jan 2, 2014 9:08:26 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * StudentOrganization generated by hbm2java
 */
public class StudentOrganization  implements java.io.Serializable {


     private Integer id;
     private Student student;
     private Organization organization;
     private String department;
     private String status;
     private Date date;
     private String user;
     private Date insertDatetime;

    public StudentOrganization() {
    }

	
    public StudentOrganization(Student student, Organization organization, Date date, Date insertDatetime) {
        this.student = student;
        this.organization = organization;
        this.date = date;
        this.insertDatetime = insertDatetime;
    }
    public StudentOrganization(Student student, Organization organization, String department, String status, Date date, String user, Date insertDatetime) {
       this.student = student;
       this.organization = organization;
       this.department = department;
       this.status = status;
       this.date = date;
       this.user = user;
       this.insertDatetime = insertDatetime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Organization getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(Organization organization) {
        this.organization = organization;
    }
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }




}


