package domain;
// Generated Jul 10, 2013 10:55:17 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Timetable generated by hbm2java
 */
public class Timetable  implements java.io.Serializable, eltc.web.DeletableInterface {


     private Integer id;
     private Course course;
     private Trainer trainerByTrainerOfficialId;
     private Trainer trainerByTrainerFactId;
     private Auditory auditory;
     private Date date;
     private boolean deleted;
     private String user;
     private Date insertDatetime;
     private Set timetableStudents = new HashSet(0);

    public Timetable() {
    }

	
    public Timetable(Course course, Trainer trainerByTrainerOfficialId, Trainer trainerByTrainerFactId, Auditory auditory, Date date, Date insertDatetime) {
        this.course = course;
        this.trainerByTrainerOfficialId = trainerByTrainerOfficialId;
        this.trainerByTrainerFactId = trainerByTrainerFactId;
        this.auditory = auditory;
        this.date = date;
        this.insertDatetime = insertDatetime;
    }
    public Timetable(Course course, Trainer trainerByTrainerOfficialId, Trainer trainerByTrainerFactId, Auditory auditory, Date date, String user, Date insertDatetime, Set timetableStudents) {
       this.course = course;
       this.trainerByTrainerOfficialId = trainerByTrainerOfficialId;
       this.trainerByTrainerFactId = trainerByTrainerFactId;
       this.auditory = auditory;
       this.date = date;
       this.user = user;
       this.insertDatetime = insertDatetime;
       this.timetableStudents = timetableStudents;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public Trainer getTrainerByTrainerOfficialId() {
        return this.trainerByTrainerOfficialId;
    }
    
    public void setTrainerByTrainerOfficialId(Trainer trainerByTrainerOfficialId) {
        this.trainerByTrainerOfficialId = trainerByTrainerOfficialId;
    }
    public Trainer getTrainerByTrainerFactId() {
        return this.trainerByTrainerFactId;
    }
    
    public void setTrainerByTrainerFactId(Trainer trainerByTrainerFactId) {
        this.trainerByTrainerFactId = trainerByTrainerFactId;
    }
    public Auditory getAuditory() {
        return this.auditory;
    }
    
    public void setAuditory(Auditory auditory) {
        this.auditory = auditory;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }
    public Set getTimetableStudents() {
        return this.timetableStudents;
    }
    
    public void setTimetableStudents(Set timetableStudents) {
        this.timetableStudents = timetableStudents;
    }

    public boolean isDeleted() {
        return deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }




}


