package domain;
// Generated Jul 10, 2013 10:55:17 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TrainerSpecialization generated by hbm2java
 */
public class TrainerSpecialization  implements java.io.Serializable {


     private Integer id;
     private Specialization specialization;
     private Trainer trainer;
     private Date date;
     private String user;
     private Date insertDatetime;

    public TrainerSpecialization() {
    }

	
    public TrainerSpecialization(Specialization specialization, Trainer trainer, Date date, Date insertDatetime) {
        this.specialization = specialization;
        this.trainer = trainer;
        this.date = date;
        this.insertDatetime = insertDatetime;
    }
    public TrainerSpecialization(Specialization specialization, Trainer trainer, Date date, String user, Date insertDatetime) {
       this.specialization = specialization;
       this.trainer = trainer;
       this.date = date;
       this.user = user;
       this.insertDatetime = insertDatetime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Specialization getSpecialization() {
        return this.specialization;
    }
    
    public void setSpecialization(Specialization specialization) {
        this.specialization = specialization;
    }
    public Trainer getTrainer() {
        return this.trainer;
    }
    
    public void setTrainer(Trainer trainer) {
        this.trainer = trainer;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }




}


