package domain;
// Generated Jul 10, 2013 10:55:17 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * TrainerCertificate generated by hbm2java
 */
public class TrainerCertificate implements java.io.Serializable {

    private Integer id;
    private Certificate certificate;
    private Trainer trainer;
    private Date date;
    private String user;
    private Date insertDatetime;

    public TrainerCertificate() {
    }

    public TrainerCertificate(Certificate certificate, Trainer trainer, Date date, Date insertDatetime) {
        this.certificate = certificate;
        this.trainer = trainer;
        this.date = date;
        this.insertDatetime = insertDatetime;
    }

    public TrainerCertificate(Certificate certificate, Trainer trainer, Date date, String user, Date insertDatetime) {
        this.certificate = certificate;
        this.trainer = trainer;
        this.date = date;
        this.user = user;
        this.insertDatetime = insertDatetime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Certificate getCertificate() {
        return certificate;
    }

    public void setCertificate(Certificate certificate) {
        this.certificate = certificate;
    }

    


    public Trainer getTrainer() {
        return this.trainer;
    }

    public void setTrainer(Trainer trainer) {
        this.trainer = trainer;
    }

    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public String getUser() {
        return this.user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public Date getInsertDatetime() {
        return this.insertDatetime;
    }

    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }
}
