package domain;
// Generated Jul 10, 2013 10:55:17 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TypeOwnership generated by hbm2java
 */
public class TypeOwnership  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String nameFull;
     private String user;
     private Date insertDatetime;
     private Set organizations = new HashSet(0);

    public TypeOwnership() {
    }

	
    public TypeOwnership(String name, String nameFull, Date insertDatetime) {
        this.name = name;
        this.nameFull = nameFull;
        this.insertDatetime = insertDatetime;
    }
    public TypeOwnership(String name, String nameFull, String user, Date insertDatetime, Set organizations) {
       this.name = name;
       this.nameFull = nameFull;
       this.user = user;
       this.insertDatetime = insertDatetime;
       this.organizations = organizations;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getNameFull() {
        return this.nameFull;
    }
    
    public void setNameFull(String nameFull) {
        this.nameFull = nameFull;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }
    public Set getOrganizations() {
        return this.organizations;
    }
    
    public void setOrganizations(Set organizations) {
        this.organizations = organizations;
    }




}


