package domain;
// Generated Jul 10, 2013 10:55:17 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

    private Integer id;
    private String login;
    private String name;
    private String password;
    private String email;
    private Date insertDatetime;
    private Set<UserVisit> userVisits = new HashSet<UserVisit>(0);

    public User() {
    }

    public User(String login, String name, String password, String email, Date insertDatetime) {
        this.login = login;
        this.name = name;
        this.password = password;
        this.email = email;
        this.insertDatetime = insertDatetime;
    }

    public User(String login, String name, String password, String email, Date insertDatetime, Set<UserVisit> userVisits) {
        this.login = login;
        this.name = name;
        this.password = password;
        this.email = email;
        this.insertDatetime = insertDatetime;
        this.userVisits = userVisits;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Date getInsertDatetime() {
        return this.insertDatetime;
    }

    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }

    public Set<UserVisit> getUserVisits() {
        return userVisits;
    }

    public void setUserVisits(Set<UserVisit> userVisits) {
        this.userVisits = userVisits;
    }
    
}
