package domain;
// Generated Jul 10, 2013 10:55:17 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vendor generated by hbm2java
 */
public class Vendor  implements java.io.Serializable, eltc.web.DictionaryInterface {


     private Integer id;
     private String name;
     private String user;
     private Date insertDatetime;
     private Set certificates = new HashSet(0);
     private Set vendorAgreements = new HashSet(0);
     private Set organizations = new HashSet(0);
     private Set courses = new HashSet(0);

    public Vendor() {
    }

	
    public Vendor(String name, Date insertDatetime) {
        this.name = name;
        this.insertDatetime = insertDatetime;
    }
    public Vendor(String name, String user, Date insertDatetime, Set certificates, Set vendorAgreements, Set organizations, Set courses) {
       this.name = name;
       this.user = user;
       this.insertDatetime = insertDatetime;
       this.certificates = certificates;
       this.vendorAgreements = vendorAgreements;
       this.organizations = organizations;
       this.courses = courses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }

    public Set getCertificates() {
        return certificates;
    }

    public void setCertificates(Set certificates) {
        this.certificates = certificates;
    }
   
    public Set getVendorAgreements() {
        return this.vendorAgreements;
    }
    
    public void setVendorAgreements(Set vendorAgreements) {
        this.vendorAgreements = vendorAgreements;
    }
    public Set getOrganizations() {
        return this.organizations;
    }
    
    public void setOrganizations(Set organizations) {
        this.organizations = organizations;
    }
    public Set getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set courses) {
        this.courses = courses;
    }




}


