package domain;
// Generated Jul 10, 2013 10:55:17 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * VendorAgreement generated by hbm2java
 */
public class VendorAgreement  implements java.io.Serializable {


     private Integer id;
     private Vendor vendor;
     private String number;
     private Date date;
     private String description;
     private String pdfFile;
     private String user;
     private Date insertDatetime;

    public VendorAgreement() {
    }

	
    public VendorAgreement(Vendor vendor, String number, Date date, Date insertDatetime) {
        this.vendor = vendor;
        this.number = number;
        this.date = date;
        this.insertDatetime = insertDatetime;
    }
    public VendorAgreement(Vendor vendor, String number, Date date, String description, String pdfFile, String user, Date insertDatetime) {
       this.vendor = vendor;
       this.number = number;
       this.date = date;
       this.description = description;
       this.pdfFile = pdfFile;
       this.user = user;
       this.insertDatetime = insertDatetime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Vendor getVendor() {
        return this.vendor;
    }
    
    public void setVendor(Vendor vendor) {
        this.vendor = vendor;
    }
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }

    public String getPdfFile() {
        return pdfFile;
    }

    public void setPdfFile(String pdfFile) {
        this.pdfFile = pdfFile;
    }




}


